package com.example.vp.consultancy.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import jakarta.validation.constraints.*;
import org.springframework.boot.context.properties.bind.DefaultValue;

/**
 * Farmer Registration Request DTO - For consultants to register their farmers
 * Only accessible to CONSULTANT users
 * @author VP Consultancy Team
 * @version 1.0
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class FarmerRegistrationRequest {

    @NotBlank(message = "Mobile number is required")
    @Pattern(regexp = "^[0-9]{10}$", message = "Mobile number must be 10 digits")
    private String mobile;

    // Password will be generated by the system for farmers; clients should not send it.
    // Kept out of the request DTO to enforce this behavior.

    @NotBlank(message = "First name is required")
    @Size(min = 2, max = 100, message = "First name must be between 2 and 100 characters")
    private String firstName;

    @NotBlank(message = "Last name is required")
    @Size(min = 2, max = 100, message = "Last name must be between 2 and 100 characters")
    private String lastName;

    private String email;

    private String addressLine;

    private String city;

    private String district = "Sangli";

    private String state = "Maharashtra"; // Default value for state

    private String postalCode;

    @Size(min = 2, max = 100, message = "Sector must be between 2 and 100 characters")
    private String sector;
}
